export const ADD_CITY = 'ADD_CITY'
export const DELETE_CITY = 'DELETE_CITY'
export const LOAD_CITY = 'LOAD_CITY'
export const GET_FIRST_DATA = 'GET_FIRST_DATA'
export const UPDATE_CITY = 'UPDATE_CITY'
